

export const FETCH_VEHICLES = 'FETCH_VEHICLES';
export const FETCH_ROUTES = 'FETCH_ROUTES';

export const FILTER_UPDATE = 'FILTER_UPDATE';
export const FETCH_ROUTE_VEHICLES = 'FETCH_ROUTE_VEHICLES';

